import fs from 'fs';
import path from 'path';
import { Tournament, BoardPairing } from '../types';
import { createInitialEmptyTournament } from '../data/initialData';

export interface PendingDraftPairing {
  round: number;
  tournamentId: string;
  boards: BoardPairing[];
  unpairedKeys: string[];
  pabKey?: string;
  gacruxSuccess: boolean;
  bbpStatus: string;
  bbpPassed: boolean;
  engineMetadata: {
    id: string;
    name: string;
    version: string;
    authoritative: boolean;
  };
  ruleLog: string[];
  createdAt: string;
}

export class TournamentStore {
  private storageFilePath: string;
  private currentTournament: Tournament;
  private pendingDrafts: Map<number, PendingDraftPairing> = new Map();
  private simulateWriteFailure: boolean = false;

  constructor(customStoragePath?: string) {
    const dataDir = path.join(process.cwd(), 'data');
    if (!fs.existsSync(dataDir)) {
      try {
        fs.mkdirSync(dataDir, { recursive: true });
      } catch {}
    }
    this.storageFilePath = customStoragePath || path.join(dataDir, 'official_tournament_state.json');
    this.currentTournament = this.loadFromDisk();
  }

  public setSimulateWriteFailure(fail: boolean) {
    this.simulateWriteFailure = fail;
  }

  private loadFromDisk(): Tournament {
    try {
      if (fs.existsSync(this.storageFilePath)) {
        const raw = fs.readFileSync(this.storageFilePath, 'utf8');
        return JSON.parse(raw);
      }
    } catch (e) {
      console.error('[TournamentStore] Error loading tournament from disk:', e);
    }
    const init = createInitialEmptyTournament('Official FIDE Dutch Championship');
    return init;
  }

  private saveToDisk(): void {
    if (this.simulateWriteFailure) {
      throw new Error('SIMULATED_DISK_WRITE_FAILURE: Storage write failed on disk.');
    }
    try {
      const dataDir = path.dirname(this.storageFilePath);
      if (!fs.existsSync(dataDir)) {
        fs.mkdirSync(dataDir, { recursive: true });
      }
      fs.writeFileSync(this.storageFilePath, JSON.stringify(this.currentTournament, null, 2), 'utf8');
    } catch (e) {
      console.error('[TournamentStore] Error saving tournament to disk:', e);
      throw e;
    }
  }

  public getOfficialTournament(): Tournament {
    // Return deep clone to prevent mutation
    return JSON.parse(JSON.stringify(this.currentTournament));
  }

  public setOfficialTournament(tourn: Tournament): void {
    this.currentTournament = JSON.parse(JSON.stringify(tourn));
    this.saveToDisk();
  }

  public getPendingDraft(round: number): PendingDraftPairing | null {
    const draft = this.pendingDrafts.get(round);
    return draft ? JSON.parse(JSON.stringify(draft)) : null;
  }

  public setPendingDraft(round: number, draft: PendingDraftPairing): void {
    this.pendingDrafts.set(round, JSON.parse(JSON.stringify(draft)));
  }

  public clearPendingDraft(round: number): void {
    this.pendingDrafts.delete(round);
  }

  /**
   * Strict 3-condition Acceptance Gate:
   * 1. Gacrux execution success
   * 2. BBP independent checker PASS
   * 3. Explicit arbiter ACCEPT
   *
   * If any condition fails, state remains completely unchanged.
   */
  public acceptPairing(
    round: number,
    options: {
      arbiterConfirmed: boolean;
      arbiterName?: string;
      notes?: string;
      customDraft?: PendingDraftPairing; // Optional explicit draft
    }
  ): { success: boolean; round: number; boards: BoardPairing[]; tournament: Tournament; arbiter?: string } {
    const draft = options.customDraft || this.pendingDrafts.get(round);

    // Gate Condition 1: Gacrux execution success
    if (!draft || !draft.gacruxSuccess) {
      throw {
        code: 'ACCEPTANCE_PRECONDITION_FAILED',
        reason: 'GACRUX_EXECUTION_MISSING',
        message: `Round ${round} pairing has not been successfully generated by authoritative Gacrux engine.`
      };
    }

    // Gate Condition 2: BBP independent checker PASS
    if (!draft.bbpPassed || draft.bbpStatus !== 'PASS') {
      throw {
        code: 'ACCEPTANCE_PRECONDITION_FAILED',
        reason: 'BBP_CHECKER_NOT_PASSED',
        message: `Round ${round} pairing cannot be accepted because BBP independent checker status is '${draft.bbpStatus}' (must be PASS).`
      };
    }

    // Gate Condition 3: Explicit arbiter ACCEPT
    if (options.arbiterConfirmed !== true) {
      throw {
        code: 'ACCEPTANCE_PRECONDITION_FAILED',
        reason: 'ARBITER_CONFIRMATION_REQUIRED',
        message: 'Explicit arbiter confirmation (arbiterConfirmed === true) is required to commit pairings to official tournament state.'
      };
    }

    // Preserve snapshot in case write fails
    const backupTournament = JSON.parse(JSON.stringify(this.currentTournament));

    try {
      // All 3 conditions satisfied: atomically commit to official tournament state
      const roundKey = String(round);
      if (!this.currentTournament.pairings) {
        this.currentTournament.pairings = {
          server: '',
          round: '1',
          results: '0',
          showScheduleOnPrint: false,
          liveBoards: {},
          finalStandingsPromptedRound: 0,
          engine: {
            mode: 'dutch',
            excluded: [],
            manualByes: {},
            fixedBoards: {},
            initialTopColor: 'w',
            needsResort: false,
            lastGeneratedRound: 0,
            lastEngineMessage: '',
            excludeRemaining: {},
            excludeRounds: {},
            roundActivationConfirmed: {},
            playerStatusCollapsed: false,
            registrationsDirty: false,
            syncedAbsent: {},
            registrationSyncedAt: '',
            registrationSyncedForRound: 0,
            registrationSyncedSignature: '',
            firstRoundRegistrationLocked: false,
            firstRoundRegistrationSyncedSignature: '',
            firstRoundRegistrationNeedsResort: false,
            firstRoundRegistrationSyncedAt: ''
          }
        };
      }

      if (!this.currentTournament.pairings.liveBoards) {
        this.currentTournament.pairings.liveBoards = {};
      }

      const committedBoards: BoardPairing[] = draft.boards.map(b => ({
        board: b.board || (b as any).boardNumber || 1,
        whiteKey: b.whiteKey,
        blackKey: b.blackKey,
        result: b.result || '-'
      }));

      this.currentTournament.pairings.liveBoards[roundKey] = committedBoards;

      // Also maintain rounds array for clients/checkers expecting rounds
      const tournPairings = this.currentTournament.pairings as any;
      if (!Array.isArray(tournPairings.rounds)) {
        tournPairings.rounds = [];
      }
      const existingRndIdx = tournPairings.rounds.findIndex((r: any) => r.round === round);
      if (existingRndIdx >= 0) {
        tournPairings.rounds[existingRndIdx] = {
          round,
          boards: committedBoards,
          completed: false
        };
      } else {
        tournPairings.rounds.push({
          round,
          boards: committedBoards,
          completed: false
        });
      }

      (this.currentTournament as any).currentRound = round;
      this.currentTournament.pairings.round = roundKey;
      this.currentTournament.pairings.engine.lastGeneratedRound = round;
      this.currentTournament.pairings.engine.lastEngineMessage = `Authoritative FIDE Dutch Round ${round} accepted by Arbiter ${options.arbiterName || 'Arbiter'}`;

      // Persist to disk atomically
      this.saveToDisk();

      // Clear pending draft upon successful commit
      this.pendingDrafts.delete(round);

      return {
        success: true,
        round,
        boards: this.currentTournament.pairings.liveBoards[roundKey],
        tournament: this.getOfficialTournament(),
        arbiter: options.arbiterName || 'Arbiter'
      };
    } catch (err: any) {
      // Rollback memory state on storage failure
      this.currentTournament = backupTournament;
      throw {
        code: 'STORAGE_COMMIT_FAILED',
        message: `Failed to persist committed tournament state: ${err.message}`
      };
    }
  }

  public resetTournament(newTourn?: Tournament): void {
    this.currentTournament = newTourn
      ? JSON.parse(JSON.stringify(newTourn))
      : createInitialEmptyTournament('Official FIDE Dutch Championship');
    this.pendingDrafts.clear();
    this.saveToDisk();
  }
}

export const tournamentStore = new TournamentStore();
